/**
 * FIGlet Font Registry
 * Dynamically generated list of all available fonts
 */
export const FIG_FONTS = {
  "1row": "/fonts/1Row.flf",
  "3d": "/fonts/3-D.flf",
  "3ddiagonal": "/fonts/3D Diagonal.flf",
  "3dascii": "/fonts/3D-ASCII.flf",
  "3x5": "/fonts/3x5.flf",
  "4max": "/fonts/4Max.flf",
  "5lineoblique": "/fonts/5 Line Oblique.flf",
  "amc3line": "/fonts/AMC 3 Line.flf",
  "amc3liv1": "/fonts/AMC 3 Liv1.flf",
  "amcaaa01": "/fonts/AMC AAA01.flf",
  "amcneko": "/fonts/AMC Neko.flf",
  "amcrazor": "/fonts/AMC Razor.flf",
  "amcrazor2": "/fonts/AMC Razor2.flf",
  "amcslash": "/fonts/AMC Slash.flf",
  "amcslider": "/fonts/AMC Slider.flf",
  "amcthin": "/fonts/AMC Thin.flf",
  "amctubes": "/fonts/AMC Tubes.flf",
  "amcuntitled": "/fonts/AMC Untitled.flf",
  "ansicompact": "/fonts/ANSI Compact.flf",
  "ansiregular": "/fonts/ANSI Regular.flf",
  "ansishadow": "/fonts/ANSI Shadow.flf",
  "ascii12": "/fonts/ASCII 12.flf",
  "ascii9": "/fonts/ASCII 9.flf",
  "asciinewroman": "/fonts/ASCII New Roman.flf",
  "acrobatic": "/fonts/Acrobatic.flf",
  "alligator": "/fonts/Alligator.flf",
  "alligator2": "/fonts/Alligator2.flf",
  "alpha": "/fonts/Alpha.flf",
  "alphabet": "/fonts/Alphabet.flf",
  "arrows": "/fonts/Arrows.flf",
  "avatar": "/fonts/Avatar.flf",
  "b1ff": "/fonts/B1FF.flf",
  "babyfacelame": "/fonts/Babyface Lame.flf",
  "babyfaceleet": "/fonts/Babyface Leet.flf",
  "banner": "/fonts/Banner.flf",
  "banner3d": "/fonts/Banner3-D.flf",
  "banner3": "/fonts/Banner3.flf",
  "banner4": "/fonts/Banner4.flf",
  "barbwire": "/fonts/Barbwire.flf",
  "basic": "/fonts/Basic.flf",
  "bear": "/fonts/Bear.flf",
  "bell": "/fonts/Bell.flf",
  "benjamin": "/fonts/Benjamin.flf",
  "bigascii12": "/fonts/Big ASCII 12.flf",
  "bigascii9": "/fonts/Big ASCII 9.flf",
  "bigchief": "/fonts/Big Chief.flf",
  "bigmoneyne": "/fonts/Big Money-ne.flf",
  "bigmoneynw": "/fonts/Big Money-nw.flf",
  "bigmoneyse": "/fonts/Big Money-se.flf",
  "bigmoneysw": "/fonts/Big Money-sw.flf",
  "bigmono12": "/fonts/Big Mono 12.flf",
  "bigmono9": "/fonts/Big Mono 9.flf",
  "big": "/fonts/Big.flf",
  "bigfig": "/fonts/Bigfig.flf",
  "binary": "/fonts/Binary.flf",
  "block": "/fonts/Block.flf",
  "blocks": "/fonts/Blocks.flf",
  "bloody": "/fonts/Bloody.flf",
  "blurvisionascii": "/fonts/BlurVision ASCII.flf",
  "bold": "/fonts/Bold.flf",
  "bolger": "/fonts/Bolger.flf",
  "braced": "/fonts/Braced.flf",
  "bright": "/fonts/Bright.flf",
  "broadwaykb": "/fonts/Broadway KB.flf",
  "broadway": "/fonts/Broadway.flf",
  "bubble": "/fonts/Bubble.flf",
  "bulbhead": "/fonts/Bulbhead.flf",
  "caligraphy": "/fonts/Caligraphy.flf",
  "caligraphy2": "/fonts/Caligraphy2.flf",
  "calvins": "/fonts/Calvin S.flf",
  "cards": "/fonts/Cards.flf",
  "catwalk": "/fonts/Catwalk.flf",
  "chiseled": "/fonts/Chiseled.flf",
  "chunky": "/fonts/Chunky.flf",
  "circle": "/fonts/Circle.flf",
  "classy": "/fonts/Classy.flf",
  "codermini": "/fonts/Coder Mini.flf",
  "coinstak": "/fonts/Coinstak.flf",
  "cola": "/fonts/Cola.flf",
  "colossal": "/fonts/Colossal.flf",
  "computer": "/fonts/Computer.flf",
  "contessa": "/fonts/Contessa.flf",
  "contrast": "/fonts/Contrast.flf",
  "cosmike": "/fonts/Cosmike.flf",
  "cosmike2": "/fonts/Cosmike2.flf",
  "crawford": "/fonts/Crawford.flf",
  "crawford2": "/fonts/Crawford2.flf",
  "crazy": "/fonts/Crazy.flf",
  "cricket": "/fonts/Cricket.flf",
  "cursive": "/fonts/Cursive.flf",
  "cyberlarge": "/fonts/Cyberlarge.flf",
  "cybermedium": "/fonts/Cybermedium.flf",
  "cybersmall": "/fonts/Cybersmall.flf",
  "cygnet": "/fonts/Cygnet.flf",
  "danc4": "/fonts/DANC4.flf",
  "dosrebel": "/fonts/DOS Rebel.flf",
  "dwhistled": "/fonts/DWhistled.flf",
  "dancingfont": "/fonts/Dancing Font.flf",
  "decimal": "/fonts/Decimal.flf",
  "defleppard": "/fonts/Def Leppard.flf",
  "deltacorpspriest1": "/fonts/Delta Corps Priest 1.flf",
  "diamfont": "/fonts/DiamFont.flf",
  "diamond": "/fonts/Diamond.flf",
  "dietcola": "/fonts/Diet Cola.flf",
  "digital": "/fonts/Digital.flf",
  "doh": "/fonts/Doh.flf",
  "doom": "/fonts/Doom.flf",
  "dotmatrix": "/fonts/Dot Matrix.flf",
  "doubleshorts": "/fonts/Double Shorts.flf",
  "double": "/fonts/Double.flf",
  "drpepper": "/fonts/Dr Pepper.flf",
  "eftichess": "/fonts/Efti Chess.flf",
  "eftifont": "/fonts/Efti Font.flf",
  "eftiitalic": "/fonts/Efti Italic.flf",
  "eftipiti": "/fonts/Efti Piti.flf",
  "eftirobot": "/fonts/Efti Robot.flf",
  "eftiwall": "/fonts/Efti Wall.flf",
  "eftiwater": "/fonts/Efti Water.flf",
  "electronic": "/fonts/Electronic.flf",
  "elite": "/fonts/Elite.flf",
  "emboss2": "/fonts/Emboss 2.flf",
  "emboss": "/fonts/Emboss.flf",
  "epic": "/fonts/Epic.flf",
  "fender": "/fonts/Fender.flf",
  "filter": "/fonts/Filter.flf",
  "firefontk": "/fonts/Fire Font-k.flf",
  "firefonts": "/fonts/Fire Font-s.flf",
  "flipped": "/fonts/Flipped.flf",
  "flowerpower": "/fonts/Flower Power.flf",
  "fontfont": "/fonts/Font Font.flf",
  "fourtops": "/fonts/Four Tops.flf",
  "fraktur": "/fonts/Fraktur.flf",
  "funface": "/fonts/Fun Face.flf",
  "funfaces": "/fonts/Fun Faces.flf",
  "futuresmooth": "/fonts/Future Smooth.flf",
  "futurethin": "/fonts/Future Thin.flf",
  "future": "/fonts/Future.flf",
  "fuzzy": "/fonts/Fuzzy.flf",
  "georgi16": "/fonts/Georgi16.flf",
  "georgia11": "/fonts/Georgia11.flf",
  "ghost": "/fonts/Ghost.flf",
  "ghoulish": "/fonts/Ghoulish.flf",
  "glenyn": "/fonts/Glenyn.flf",
  "goofy": "/fonts/Goofy.flf",
  "gothic": "/fonts/Gothic.flf",
  "graceful": "/fonts/Graceful.flf",
  "gradient": "/fonts/Gradient.flf",
  "graffiti": "/fonts/Graffiti.flf",
  "greek": "/fonts/Greek.flf",
  "heartleft": "/fonts/Heart Left.flf",
  "heartright": "/fonts/Heart Right.flf",
  "henry3d": "/fonts/Henry 3D.flf",
  "hex": "/fonts/Hex.flf",
  "hieroglyphs": "/fonts/Hieroglyphs.flf",
  "hollywood": "/fonts/Hollywood.flf",
  "horizontalleft": "/fonts/Horizontal Left.flf",
  "horizontalright": "/fonts/Horizontal Right.flf",
  "icl1900": "/fonts/ICL-1900.flf",
  "impossible": "/fonts/Impossible.flf",
  "invita": "/fonts/Invita.flf",
  "isometric1": "/fonts/Isometric1.flf",
  "isometric2": "/fonts/Isometric2.flf",
  "isometric3": "/fonts/Isometric3.flf",
  "isometric4": "/fonts/Isometric4.flf",
  "italic": "/fonts/Italic.flf",
  "ivrit": "/fonts/Ivrit.flf",
  "jsblockletters": "/fonts/JS Block Letters.flf",
  "jsbracketletters": "/fonts/JS Bracket Letters.flf",
  "jscapitalcurves": "/fonts/JS Capital Curves.flf",
  "jscursive": "/fonts/JS Cursive.flf",
  "jsstickletters": "/fonts/JS Stick Letters.flf",
  "jacky": "/fonts/Jacky.flf",
  "jazmine": "/fonts/Jazmine.flf",
  "jerusalem": "/fonts/Jerusalem.flf",
  "katakana": "/fonts/Katakana.flf",
  "kban": "/fonts/Kban.flf",
  "keyboard": "/fonts/Keyboard.flf",
  "knob": "/fonts/Knob.flf",
  "kontoslant": "/fonts/Konto Slant.flf",
  "konto": "/fonts/Konto.flf",
  "lcd": "/fonts/LCD.flf",
  "larry3d2": "/fonts/Larry 3D 2.flf",
  "larry3d": "/fonts/Larry 3D.flf",
  "lean": "/fonts/Lean.flf",
  "letter": "/fonts/Letter.flf",
  "letters": "/fonts/Letters.flf",
  "lildevil": "/fonts/Lil Devil.flf",
  "lineblocks": "/fonts/Line Blocks.flf",
  "linux": "/fonts/Linux.flf",
  "lockergnome": "/fonts/Lockergnome.flf",
  "madrid": "/fonts/Madrid.flf",
  "marquee": "/fonts/Marquee.flf",
  "maxfour": "/fonts/Maxfour.flf",
  "merlin1": "/fonts/Merlin1.flf",
  "merlin2": "/fonts/Merlin2.flf",
  "mike": "/fonts/Mike.flf",
  "mini": "/fonts/Mini.flf",
  "mirror": "/fonts/Mirror.flf",
  "mnemonic": "/fonts/Mnemonic.flf",
  "modular": "/fonts/Modular.flf",
  "mono12": "/fonts/Mono 12.flf",
  "mono9": "/fonts/Mono 9.flf",
  "morse": "/fonts/Morse.flf",
  "morse2": "/fonts/Morse2.flf",
  "moscow": "/fonts/Moscow.flf",
  "mshebrew210": "/fonts/Mshebrew210.flf",
  "muzzle": "/fonts/Muzzle.flf",
  "nscript": "/fonts/NScript.flf",
  "ntgreek": "/fonts/NT Greek.flf",
  "nvscript": "/fonts/NV Script.flf",
  "nancyjfancy": "/fonts/Nancyj-Fancy.flf",
  "nancyjimproved": "/fonts/Nancyj-Improved.flf",
  "nancyjunderlined": "/fonts/Nancyj-Underlined.flf",
  "nancyj": "/fonts/Nancyj.flf",
  "nipples": "/fonts/Nipples.flf",
  "o8": "/fonts/O8.flf",
  "os2": "/fonts/OS2.flf",
  "octal": "/fonts/Octal.flf",
  "ogre": "/fonts/Ogre.flf",
  "oldbanner": "/fonts/Old Banner.flf",
  "pagga": "/fonts/Pagga.flf",
  "patorjkscheese": "/fonts/Patorjk's Cheese.flf",
  "patorjkhex": "/fonts/Patorjk-HeX.flf",
  "pawp": "/fonts/Pawp.flf",
  "peaksslant": "/fonts/Peaks Slant.flf",
  "peaks": "/fonts/Peaks.flf",
  "pebbles": "/fonts/Pebbles.flf",
  "pepper": "/fonts/Pepper.flf",
  "poison": "/fonts/Poison.flf",
  "puffy": "/fonts/Puffy.flf",
  "puzzle": "/fonts/Puzzle.flf",
  "pyramid": "/fonts/Pyramid.flf",
  "rammstein": "/fonts/Rammstein.flf",
  "rebel": "/fonts/Rebel.flf",
  "rectangles": "/fonts/Rectangles.flf",
  "redphoenix": "/fonts/Red Phoenix.flf",
  "relief": "/fonts/Relief.flf",
  "relief2": "/fonts/Relief2.flf",
  "reverse": "/fonts/Reverse.flf",
  "roman": "/fonts/Roman.flf",
  "rot13": "/fonts/Rot13.flf",
  "rotated": "/fonts/Rotated.flf",
  "rounded": "/fonts/Rounded.flf",
  "rowancap": "/fonts/Rowan Cap.flf",
  "rozzo": "/fonts/Rozzo.flf",
  "rubifont": "/fonts/RubiFont.flf",
  "runic": "/fonts/Runic.flf",
  "runyc": "/fonts/Runyc.flf",
  "sblood": "/fonts/S Blood.flf",
  "slscript": "/fonts/SL Script.flf",
  "santaclara": "/fonts/Santa Clara.flf",
  "script": "/fonts/Script.flf",
  "serifcap": "/fonts/Serifcap.flf",
  "shadedblocky": "/fonts/Shaded Blocky.flf",
  "shadow": "/fonts/Shadow.flf",
  "shimrod": "/fonts/Shimrod.flf",
  "short": "/fonts/Short.flf",
  "slantrelief": "/fonts/Slant Relief.flf",
  "slant": "/fonts/Slant.flf",
  "slide": "/fonts/Slide.flf",
  "smallascii12": "/fonts/Small ASCII 12.flf",
  "smallascii9": "/fonts/Small ASCII 9.flf",
  "smallblock": "/fonts/Small Block.flf",
  "smallbraille": "/fonts/Small Braille.flf",
  "smallcaps": "/fonts/Small Caps.flf",
  "smallisometric1": "/fonts/Small Isometric1.flf",
  "smallkeyboard": "/fonts/Small Keyboard.flf",
  "smallmono12": "/fonts/Small Mono 12.flf",
  "smallmono9": "/fonts/Small Mono 9.flf",
  "smallpoison": "/fonts/Small Poison.flf",
  "smallscript": "/fonts/Small Script.flf",
  "smallshadow": "/fonts/Small Shadow.flf",
  "smallslant": "/fonts/SmallSlant.flf",
  "smalltengwar": "/fonts/Small Tengwar.flf",
  "small": "/fonts/Small.flf",
  "smallslantd": "/fonts/SmallSlantd.flf",
  "soft": "/fonts/Soft.flf",
  "speed": "/fonts/Speed.flf",
  "spliff": "/fonts/Spliff.flf",
  "stacey": "/fonts/Stacey.flf",
  "stampate": "/fonts/Stampate.flf",
  "stampatello": "/fonts/Stampatello.flf",
  "standard": "/fonts/Standard.flf",
  "starstrips": "/fonts/Star Strips.flf",
  "starwars": "/fonts/StarWars.flf",
  "stellar": "/fonts/Stellar.flf",
  "stforek": "/fonts/Stforek.flf",
  "stickletters": "/fonts/Stick Letters.flf",
  "stop": "/fonts/Stop.flf",
  "straight": "/fonts/Straight.flf",
  "strongerthanall": "/fonts/Stronger Than All.flf",
  "subzero": "/fonts/Sub-Zero.flf",
  "swampland": "/fonts/Swamp Land.flf",
  "swan": "/fonts/Swan.flf",
  "sweet": "/fonts/Sweet.flf",
  "this": "/fonts/THIS.flf",
  "tanja": "/fonts/Tanja.flf",
  "tengwar": "/fonts/Tengwar.flf",
  "term": "/fonts/Term.flf",
  "terrace": "/fonts/Terrace.flf",
  "test1": "/fonts/Test1.flf",
  "theedge": "/fonts/The Edge.flf",
  "thick": "/fonts/Thick.flf",
  "thin": "/fonts/Thin.flf",
  "thorned": "/fonts/Thorned.flf",
  "threepoint": "/fonts/Three Point.flf",
  "ticksslant": "/fonts/Ticks Slant.flf",
  "ticks": "/fonts/Ticks.flf",
  "tiles": "/fonts/Tiles.flf",
  "tinkertoy": "/fonts/Tinker-Toy.flf",
  "tmplr": "/fonts/Tmplr.flf",
  "tombstone": "/fonts/Tombstone.flf",
  "train": "/fonts/Train.flf",
  "trek": "/fonts/Trek.flf",
  "tsalagi": "/fonts/Tsalagi.flf",
  "tubular": "/fonts/Tubular.flf",
  "twisted": "/fonts/Twisted.flf",
  "twopoint": "/fonts/Two Point.flf",
  "usaflag": "/fonts/USA Flag.flf",
  "univers": "/fonts/Univers.flf",
  "upsidedowntext": "/fonts/Upside Down Text.flf",
  "varsity": "/fonts/Varsity.flf",
  "wavescape": "/fonts/Wavescape.flf",
  "wavy": "/fonts/Wavy.flf",
  "weird": "/fonts/Weird.flf",
  "wetletter": "/fonts/Wet Letter.flf",
  "whimsy": "/fonts/Whimsy.flf",
  "wideterm": "/fonts/WideTerm.flf",
  "wow": "/fonts/Wow.flf",
  "miniwi": "/fonts/miniwi.flf"
} as const;

export type FigFontName = keyof typeof FIG_FONTS;